### ISSUE TITLE
Acronym Creation with Cracken

### ISSUE THREAD

**Issue by mtisec** [shmuelamar/cracken#2]
Is it possible to create acronyms of words with cracken? I want to provide a list of words and want the acronym for the word:
For example "GitHubMegaHost" should create at least `GHMH`, but maybe also shorter acronyms skipping one or more letters.

Is that something you could do with Cracken or would you rather use some other tool for that or just script it?

**Comment by shmuelamar** [comment]
Hi @mtisec, Cracken can surely help you with it. Here is one example:
1. use Cracken to identify the most important / expressive words on your wordlist like this `cracken create -f words.txt dict.lst` (see help and docs for more info on how to use `cracken create`)
2. now to get a list of possible acronyms from your original wordlist, we'll use dict.lst in 2 possible ways i can think of:
  * use an algorithm to find all possible splits of a word from the given dictionary and run it on all words of your wordlist (e.g. use  [this](https://codereview.stackexchange.com/a/197573) example)
  * extend on `cracken entropy` logic which finds the minimal entropy of the given password by splitting it into words from your wordlist (dict.lst) and individual chars. you can start by taking a look [here](https://github.com/shmuelamar/cracken/blob/main/src/runner.rs#L460) and [here](https://github.com/shmuelamar/cracken/blob/main/src/password_entropy.rs#L63). The entropy estimator uses the A-Star algorithm and can be used to find the n-th minimal splits. so if you not only want a random, all or one possible acronym you can use it to have a sorted list by estimated entropy (roughly how common the split pattern is) and you can decide how big your acronyms list is.

I'm open to suggestions if you have any useful additions to the tool that you wish to add.

Sorry for the delayed response, missed your issue in my inbox 🙂

**Comment by shmuelamar** [comment]
closing for now, thanks for your feedback. let me know if it helped.
