### ISSUE TITLE
Improve docs

### ISSUE THREAD

**Issue by ventaquil** [shmuelamar/cracken#4]
[Docs](https://docs.rs/cracken) does not contain any useful usage examples.

Items should contain at least some descriptions (basic examples are nice to have).

**Comment by shmuelamar** [comment]
You are right, the main focus of this project is a command line tool. I did not add documentation for the project itself only the CLI help.

Can you share your specific interest in this project so i can help and maybe focus my (limited) time around specific areas in the project to clarify them with docs?
